name: Metrics
on:
  # Schedule updates
  schedule: [ { cron: "0 0 1,10,20 * *" } ]
  # Lines below let you run workflow manually and on each commit
  push: { branches: [ "master" ] }
  workflow_dispatch:

jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Personal metrics (left)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-left.svg
          token: ${{ secrets.README }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Lines
          plugin_lines: yes
          # Traffic
          plugin_traffic: yes
          # Follow-up
          plugin_followup: yes
          # Isometric calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # Habits
          plugin_habits: yes
          plugin_habits_from: 400
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Asia/ShangHai
          # Languages
          plugin_languages: yes
          plugin_languages_ignored: "" # List of comma separated languages to ignore
          plugin_languages_skipped: "" # List of comma separated repositories to skip
          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut  # Hide octonaut achievement
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets param
          # Projects
          plugin_projects: yes
          plugin_projects_limit: 5
          plugin_projects_descriptions: yes

      - name: 🦑 Personal metrics (right)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-right.svg
          # Your GitHub token
          token: NOT_NEEDED
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Topics
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_limit: 15
          # PageSpeed
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://ormissia.github.io
