name: Metrics
on:
  # Schedule updates
  schedule: [ { cron: "0 0 1,10,20 * *" } ]
  # Lines below let you run workflow manually and on each commit
  push: { branches: [ "master" ] }
  workflow_dispatch:

jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: 🦑 Personal metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.README }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Lines
          # plugin_lines: yes
          # # Traffic
          # plugin_traffic: yes
          # Follow-up
          # plugin_followup: yes
          # Isometric calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # # Habits
          # plugin_habits: yes
          # plugin_habits_from: 400
          # plugin_habits_days: 14
          # plugin_habits_facts: yes
          # plugin_habits_charts: yes
          # config_timezone: Asia/ShangHai
          # Languages
          plugin_languages: yes
          plugin_languages_ignored: "" # List of comma separated languages to ignore
          plugin_languages_skipped: "" # List of comma separated repositories to skip
          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut  # Hide octonaut achievement
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets param
   
