name: Metrics
on:
  # Schedule updates
  schedule: [ { cron: "0 0 * * *" } ]
  # Lines below let you run workflow manually and on each commit
  push: { branches: [ "master" ] }
  workflow_dispatch:

jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Personal metrics (left)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-left.svg
          token: ${{ secrets.README }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Lines
          plugin_lines: yes
          # Traffic
          plugin_traffic: yes
          # Follow-up
          plugin_followup: yes
          # Isometric calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # Languages
          plugin_languages: yes
          plugin_languages_ignored: "" # List of comma separated languages to ignore
          plugin_languages_skipped: "" # List of comma separated repositories to skip
          # PageSpeed
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: no
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://ormissia.github.io
          # Projects
          plugin_projects: yes
          plugin_projects_limit: 5
          plugin_projects_descriptions: yes

      - name: 🦑 Personal metrics (right)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-right.svg
          token: NOT_NEEDED
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_music: yes
          plugin_music_playlist: ${{ secrets.MUSIC_PLAYLIST }}
          plugin_music_limit: 4
          config_order: anilist, music
